markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 爱丸
host: http://jiayouxjh.github.io
desc: 在通往牛逼的路上，我一路裸奔=。=|||

custom:
    category:
        default: Default Category
        another: Another Category
    categories:
        - name:  default
        title: 111

        - name:  another
        title: 222

    scrollingLoadCount: 5                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 徐基慧
        email: xjhssg@gmail.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: jiayouxjh                           # GitHub账号
        gravatar: ad6f3085ea45499fdf3960859c2265e1  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
